import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const HederComponent = () => {
  return (
    <div className='header h-14 bg-teal-300 border-black sticky top-0'>
      <h1 className='text-slate-50 font-bold text-3xl pt-2 pl-2'>
        @SmartDemo
      </h1>
    </div>
  )
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        <HederComponent />
        <a href='/setting'>設定</a>
        <div>
          {children}
        </div>
      </body>
    </html>
  )
}
