class ApplicationRecord < ActiveRecord::Base
end
class EmployeeQualification::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class EmployeePersonnelChange::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class PayrollGroupAttendanceItem::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class PayrollGroupPaymentItem::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class PayrollGroupDeductionItem::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class EmployeeSalary::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class EmployeeSalaryPaymentItem::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class EmployeeSalaryAttendanceItem::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class EmployeeSalaryDeductionItem::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class EmployeeBank::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class EmployeeFamily::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class EmployeePayrollGroup::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class BankBranch::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class ActiveRecord::Associations::CollectionProxy < ActiveRecord::Relation
end
class ActiveRecord::Relation < Object
end
module ActiveRecord::Associations
end
